[package]
name = "ptop"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
sysinfo = "0.32.0"
humantime = "2.1.0"
humansize = "2.0.0"
strum = { version = "0.26.0", features = ["derive"] }
